### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by socktow** [piorrro33/overlay#10]
:< it still run , but havent anything in client

**Comment by HarmfulBreeze** [comment]
The overlay has been broken by the 10.10 patch. Will be fixed with the next release.

**Comment by HarmfulBreeze** [comment]
try with v1.3.1 and tell me how it goes https://github.com/piorrro33/overlay/releases/tag/v1.3.1

**Comment by HarmfulBreeze** [comment]
Closing until further information is provided.
