### ISSUE TITLE
About stream_bg

### ISSUE THREAD

**Issue by Laezor** [piorrro33/overlay#14]
I tried to add a stream_bg.png to the web/img/custom directory, but when I run the program again its still green screen. Do I have to do something else?

**Comment by HarmfulBreeze** [comment]
Hi,
stream_bg only replaces the green screen at the middle of the screen while drafting. It does not replace the green screen while waiting for the draft to start, this one cannot be customized at the moment. That's something I could implement if it's something you're really interested in.
