### ISSUE TITLE
How do you change the font?

### ISSUE THREAD

**Issue by rayceyiii** [piorrro33/overlay#15]
How do you change the font with size and color?

**Comment by HarmfulBreeze** [comment]
Hello, you can change the font by placing the font file in `web/fonts`. There's a README file to help you in the folder.

Font colors can be customized in `config.conf`.

**Comment by rayceyiii** [comment]
> Hello, you can change the font by placing the font file in `web/fonts`. There's a README file to help you in the folder.
> 
> Font colors can be customized in `config.conf`.

Sorry mate im new to a java and its configs.. In the config, how do you change it like for example in the following line : "name": "Blue team",
        "rgbColor": [
          0,
          191,
          255

whats the 0, the 191 and the 255?  Is thsi compatible with color code? Like i just want to change the font color which is "ffffff"
