### ISSUE TITLE
how to change the color of the team names ?

### ISSUE THREAD

**Issue by ihabdz55** [piorrro33/overlay#21]
like the title i tried going in config.json in web etc ... but idon't know exacly where to go if you can show me a screen shot of the code plz

**Comment by HarmfulBreeze** [comment]
Hi, open `config.conf` in any text editor and modify 0 0 0 with the RGB values of your choice: ![](https://i.imgur.com/asTkUoH.png)

Feel free to use any color picker to get the color you want

**Comment by ihabdz55** [comment]
thank you so much
