### ISSUE TITLE
[Feature Req] Easy way to update team info

### ISSUE THREAD

**Issue by Saamstep** [piorrro33/overlay#23]
Possibly through OSC or a plain-text file to easily update team info on the fly, mid broadcast faster would be wonderful!

**Comment by HarmfulBreeze** [comment]
Hi, you can already do so by editing `config.conf` and saving the file, the display will be updated automatically :)

**Comment by Saamstep** [comment]
Hi, 
I use that now but I am looking for a way to automate the system by pulling data from other data sources, was wondering if it would be possible to even build in an http api to send POST requests to update specific fields?

**Comment by HarmfulBreeze** [comment]
that's not planned, but you can try to parse the file as a JSON, edit the desired fields, then write it back and it should achieve what you desire
