### ISSUE TITLE
Summoners Spells not updating 

### ISSUE THREAD

**Issue by remix867** [piorrro33/overlay#9]
When locking in a Champ, the Spells are displayed correctly. But when I update the spells after locking in the champ it won't update the spells in the overlay.

I am using overlay 32 Bit version.

**Comment by HarmfulBreeze** [comment]
Hey @remix867, I tried to reproduce the issue but I wasn't able to, could you please give me exact reproduction steps?

**Comment by HarmfulBreeze** [comment]
maybe v1.3.1 fixes it? https://github.com/piorrro33/overlay/releases/tag/v1.3.1

**Comment by HarmfulBreeze** [comment]
Closing until further information is provided.
